name: unix_conf_management
description: My Ansible collection of roles for config managing Linux and MACOS.
authors:
  - Jacob Schreuder
license:
  - Apache-2.0
namespace: jacobvhs
version: 2.1.0
readme: README.md
repository: https://github.com/JacobVHS/jacobvhs_ansible_galaxy

