---

- name: Bail out if operating system is not macOS
  fail:
    msg: "Unsupported OS detected! Ansible OS Family is {{ ansible_os_family }}."
  when: ansible_os_family != 'Darwin'

- name: Install XCode Command Line Tools
  ansible.builtin.include_tasks:
    file: xcode.yaml

- name: Install Required Homebrew Packages
  ansible.builtin.include_tasks:
    file: brew.yaml

- name: Configure the shell
  ansible.builtin.include_tasks:
    file: shell_conf.yaml

- name: Configure text editors
  ansible.builtin.include_tasks:
    file: editor.yaml
