---
- name: Ansible | Install required pip packages
  ansible.builtin.pip:
    name:
      - ansible-lint
      - ansible-dev-environment
      - ansible-creator
    extra_args: --user

- name: Fonts | Create a directory if it does not exist
  ansible.builtin.file:
    path: "/Users/{{ username }}/.local/share/fonts"
    state: directory
    mode: "0755"

- name: Fonts | Change file ownership, group and permissions
  ansible.builtin.file:
    path: "/Users/{{ username }}/.local/share/fonts"
    owner: "{{ username }}"
    group: "staff"
    mode: "0755"

- name: Fonts | Download Nerdfonts CascadiaCode
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/CascadiaCode.zip
    dest: "/Users/{{ username }}/.local/share/fonts/CascadiaCode.zip"
    mode: "0444"

- name: Fonts | Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "/Users/{{ username }}/.local/share/fonts/CascadiaCode.zip"
    dest: "/Users/{{ username }}/.local/share/fonts/"
    remote_src: true

- name: Shell | Collect the git status prompt shell script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
    dest: "/Users/{{ username }}/.git-prompt.sh"
    mode: "0777"

- name: Shell | Push out bashrc template
  ansible.builtin.template:
    src: "templates/bashrc.j2"
    dest: "/Users/{{ username }}/.bashrc"
    mode: "0644"

- name: Shell | Push out tmux.conf template
  ansible.builtin.template:
    src: "templates/tmux.conf.j2"
    dest: "/Users/{{ username }}/.tmux.conf"
    mode: "0644"

- name: BAT | Add catppuccin mocha theme
  ansible.builtin.shell:
    cmd: 'mkdir -p "$(bat --config-dir)/themes"'

- name: BAT | Add catppuccin mocha theme
  ansible.builtin.shell:
    cmd: 'wget -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme'

- name: BAT | Re-cache BAT
  ansible.builtin.shell:
    cmd: "bat cache --build"

- name: Neovim | Clone NvChad starter config if it doesn't exist
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory
    mode: "0755"

- name: Neovim | Git clone NvChad starter config
  ansible.builtin.git:
    repo: https://github.com/NvChad/starter
    dest: ~/.config/nvim
    clone: true
    update: false
